Master integration
linkedin-replica/jobs pull request #8
Opened 2018-04-21 18:15 UTC by BaherAbdelmalek

2018-04-21 18:16 UTC, BaherAbdelmalek commented
@Nabila63Ahmed

2018-05-01 18:24 UTC, mostafa-abdullah requested changes

2018-05-01 18:24 UTC, mostafa-abdullah commented on .idea/compiler.xml
> -      <module name="jobs" target="1.5" />
Please put the .idea folder in gitignore and untrack it
```
git rm --cached -r .idea/
```

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/commands/impl/UserApplyForJobCommand.java
> +        // get notifications from db
what notifications?

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/commands/impl/ViewAppliedJobsCommand.java
> +            ArrayList<ReturnedJob> jobs = jobsHandler.getAppliedJobs((String)args.get("userId"));
Please adjust the indentation

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/database/DatabaseInstance.java
> +public class DatabaseInstance {
Where do you use this class?

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/database/DatabaseInstance.java
> +        try {
You shouldn't catch any exceptions here

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/database/handlers/JobsHandler.java
> +    public void user_save_job(String userId,String jobId) throws SQLException;
please use camel case convention :`userSaveJob`

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/database/handlers/JobsHandler.java
> +    public boolean RespondToJobsAsCompany(String userId,String jobId,String applicantId, int status) throws SQLException;
please use camel case convention: `respondTo...`

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/database/handlers/impl/ArangoSQLJobsHandler.java
> +    public boolean ValidateCompany(String userId, String companyId){
`validateCompany` .. Camel case

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/main/java/com/linkedin/replica/jobs/models/lightUser.java
> +    @DocumentField(DocumentField.Type.KEY)
Where to we use light models? If they are no longer needed please delete them. Also class names should be capitalized.

2018-05-01 18:24 UTC, mostafa-abdullah commented on src/test/java/Core/ArangoHandlerTest.java
> +//    @Test
Why are all the tests commented?

2018-05-01 18:24 UTC, mostafa-abdullah commented on target/classes/config/controller.config
> +controller.request.body.setmaxthreadcount=controller.func.max_thread_count
Please put the target in gitignore and untrack it

2018-05-01 21:29 UTC, mostafa-abdullah approved these changes

2018-05-01 21:30 UTC, merged